[build]
  # Publish directory
  publish = "dist"

  # Default build command.
  command = "npm run build"

[[redirects]]
  from = "https://sanity-schema.netlify.app/*"
  to = "https://sanity-schema.simeongriggs.dev/:splat"
  status = 301
  force = true