[build]
  # Publish directory
  publish = "dist"

  # Default build command.
  command = "npm run build"

[[redirects]]
  from = "https://tailwind-css-palette-generator.netlify.com/*"
  to = "https://tailwind.simeongriggs.dev/:splat"
  status = 301
  force = true